Repository letdummy/Simple-to-Advance, pull requests merged in 2022-10, with the labels that each got.

#2 Chess Related Webpage using basic Html Css
  2.Basic Static WebPages Chess Content or rules/.gitattributes
  2.Basic Static WebPages Chess Content or rules/About-Chess.html
  2.Basic Static WebPages Chess Content or rules/README.md
  2.Basic Static WebPages Chess Content or rules/a.txt
  2.Basic Static WebPages Chess Content or rules/rules.html
  2.Basic Static WebPages Chess Content or rules/stylesheet.css
Labels: good first issue, hacktoberfest-accepted

#3 mars rover img
  03. Mars Rover Image/index.html
  03. Mars Rover Image/jquery-3.6.1.js
  03. Mars Rover Image/script.js
Labels: hacktoberfest-accepted

#4 feat: add tribute page
  Tribute_Page/images/tribute-page-main-image.jpg
  Tribute_Page/index.html
  Tribute_Page/styles.css
Labels: hacktoberfest-accepted, Awesome

#5 Added a folder for food website landing page
  05. Food Website Landing Page/image.png
  05. Food Website Landing Page/index.html
  05. Food Website Landing Page/style.css
Labels: hacktoberfest-accepted, kick-starter

#8 Added Stopwatch web as my contribution
  06. Stopwatch/index.html
  06. Stopwatch/script.js
  06. Stopwatch/style.css
Labels: hacktoberfest-accepted, Awesome

#9 Drum kit website
  07. Drum Kit/.DS_Store
  07. Drum Kit/images/crash.png
  07. Drum Kit/images/kick.png
  07. Drum Kit/images/snare.png
  07. Drum Kit/images/tom1.png
  07. Drum Kit/images/tom2.png
  07. Drum Kit/images/tom3.png
  07. Drum Kit/images/tom4.png
  07. Drum Kit/index.html
  07. Drum Kit/index.js
  07. Drum Kit/sounds/crash.mp3
  07. Drum Kit/sounds/kick-bass.mp3
  07. Drum Kit/sounds/snare.mp3
  07. Drum Kit/sounds/tom-1.mp3
  07. Drum Kit/sounds/tom-2.mp3
  07. Drum Kit/sounds/tom-3.mp3
  07. Drum Kit/sounds/tom-4.mp3
  07. Drum Kit/styles.css
Labels: hacktoberfest-accepted, Awesome, kick-starter

#20 PingPong project
  08. PING PONG/index.html
  08. PING PONG/lisa-keffer-i0kB5B9J8Ds-unsplash.jpg
  08. PING PONG/script.js
Labels: hacktoberfest-accepted, kick-starter

#16 Added Random Choice Picker Project
  09.Random Choice Picker/index.html
  09.Random Choice Picker/script.js
  09.Random Choice Picker/style.css
Labels: hacktoberfest-accepted, Awesome

#17 Added a game Guess My Number
  10. Guess-My-Number/README.md
  10. Guess-My-Number/index.html
  10. Guess-My-Number/script.js
  10. Guess-My-Number/style.css
Labels: good first issue, hacktoberfest-accepted

#22 Added ToDo Web app project
  11. To_Do Web App/.gitignore
  11. To_Do Web App/README.md
  11. To_Do Web App/firebase.json
  11. To_Do Web App/package-lock.json
  11. To_Do Web App/package.json
  11. To_Do Web App/public/favicon.ico
  11. To_Do Web App/public/index.html
  11. To_Do Web App/public/logo192.png
  11. To_Do Web App/public/logo512.png
  11. To_Do Web App/public/manifest.json
  11. To_Do Web App/public/robots.txt
  11. To_Do Web App/src/App.css
  11. To_Do Web App/src/App.js
  11. To_Do Web App/src/App.test.js
  11. To_Do Web App/src/components/Footer.js
  11. To_Do Web App/src/components/Footer.module.css
  11. To_Do Web App/src/components/TodoItem.js
  11. To_Do Web App/src/components/TodoItem.module.css
  11. To_Do Web App/src/index.css
  11. To_Do Web App/src/index.js
  11. To_Do Web App/src/logo.svg
  11. To_Do Web App/src/reportWebVitals.js
  11. To_Do Web App/src/setupTests.js
Labels: enhancement, hacktoberfest-accepted

#27 added survey form html code
  11. Survey Form/README.md
  11. Survey Form/index.html
Labels: hacktoberfest-accepted

#29 Music Responsive Landing Page Project!
  Music Site Landing Page/img.png
  Music Site Landing Page/index.html
  Music Site Landing Page/index.js
  Music Site Landing Page/resp.css
  Music Site Landing Page/style.css
Labels: good first issue, hacktoberfest-accepted, kick-starter

#30 Added a folder for Crypto currency website with source codes
  06. Crypto Currency website codes/image1.png
  06. Crypto Currency website codes/index.html
  06. Crypto Currency website codes/style.css
Labels: hacktoberfest-accepted

#31 Added Calculator Project
  12 . Calculator/calculator.css
  12 . Calculator/index.html
  12 . Calculator/script.js
  12 . Calculator/style.css
Labels: enhancement, hacktoberfest-accepted

#39 Animated modern sign up form
  16. Awesome Animated Signup Formsignup.html
Labels: hacktoberfest-accepted

#40 added_simple_library_management_system
  16. Simple Library Management System/DBConnection.php
  16. Simple Library Management System/DisplayBooks.php
  16. Simple Library Management System/EnterBooks.php
  16. Simple Library Management System/InsertBooks.php
  16. Simple Library Management System/SearchBooks.php
Labels: enhancement, hacktoberfest-accepted, Awesome

#41 Added Pong Game using JS
  18. Pong Game/index.html
  18. Pong Game/script.js
  18. Pong Game/style.css
Labels: hacktoberfest-accepted

#48 Twitter
  16. Twitter-clone-html-css/.gitattributes
  16. Twitter-clone-html-css/index.html
  16. Twitter-clone-html-css/js.jpg
  16. Twitter-clone-html-css/twitter.css
  16. Twitter-clone-html-css/you.jpg
Labels: enhancement, hacktoberfest-accepted, Awesome

#50 Added RGB-color-game-master at index number 18. Also made necessary changes to README.md
  18. RGB-color-game-master/index.html
  18. RGB-color-game-master/main.js
  18. RGB-color-game-master/style.css
  README.md
Labels: hacktoberfest-accepted

#60 Made a drawing-app
  drawing-app/index.html
  drawing-app/script.js
  drawing-app/style.css
Labels: hacktoberfest-accepted, Ready to Merge

#66 Added Memory Card Game App
  25. Memory Card Game/.gitignore
  25. Memory Card Game/README.md
  25. Memory Card Game/babel.config.js
  25. Memory Card Game/helper/card.js
  25. Memory Card Game/package-lock.json
  25. Memory Card Game/package.json
  25. Memory Card Game/public/favicon.ico
  25. Memory Card Game/public/index.html
  25. Memory Card Game/src/App.vue
  25. Memory Card Game/src/assets/angular.svg
  25. Memory Card Game/src/assets/arrow.svg
  25. Memory Card Game/src/assets/aurelia.svg
  25. Memory Card Game/src/assets/backbone.svg
  25. Memory Card Game/src/assets/ember.svg
  25. Memory Card Game/src/assets/js-badge.svg
  25. Memory Card Game/src/assets/logo.png
  25. Memory Card Game/src/assets/react.svg
  25. Memory Card Game/src/assets/vue.svg
  25. Memory Card Game/src/components/CardContainer.vue
  25. Memory Card Game/src/components/CardItem.vue
  25. Memory Card Game/src/components/DashBoard.vue
  25. Memory Card Game/src/components/Modal.vue
  25. Memory Card Game/src/components/ScoreBoard.vue
  25. Memory Card Game/src/components/Title.vue
  25. Memory Card Game/src/main.js
  25. Memory Card Game/utils/game.js
  25. Memory Card Game/yarn.lock
Labels: hacktoberfest-accepted, Ready to Merge

#54 Added Snake Game
  Snake Game/.vscode/settings.json
  Snake Game/Img1.png
  Snake Game/Snake Game Demo.mp4
  Snake Game/back.jpg
  Snake Game/bmusic.mp3
  Snake Game/change direction.wav
  Snake Game/css/style.css
  Snake Game/game over.wav
  Snake Game/gulp.wav
  Snake Game/index.html
  Snake Game/js/index.js
Labels: good first issue, hacktoberfest-accepted

#56 A Joke Teller Webpage by abhayst007
  11. Joke Teller/README.md
  11. Joke Teller/Sketchy.ttf
  11. Joke Teller/index.html
  11. Joke Teller/pattern.png
  11. Joke Teller/script.js
  11. Joke Teller/style.css
Labels: hacktoberfest-accepted

#58 Random Color Generator with Hex Code
  19. Random Color Generator with Hex Codes/index.html
  19. Random Color Generator with Hex Codes/script.js
  19. Random Color Generator with Hex Codes/style.css
Labels: good first issue, hacktoberfest-accepted

#68 Updated table of contents
  README.md
Labels: documentation, hacktoberfest-accepted

#35 added landing page car rent
  15. Landing Page Car Rent/README.md
  15. Landing Page Car Rent/assets/Rate.png
  15. Landing Page Car Rent/assets/check.png
  15. Landing Page Car Rent/assets/favicon_io/android-chrome-192x192.png
  15. Landing Page Car Rent/assets/icon_24hrs.png
  15. Landing Page Car Rent/assets/icon_complete.png
  15. Landing Page Car Rent/assets/icon_facebook.png
  15. Landing Page Car Rent/assets/icon_instagram.png
  15. Landing Page Car Rent/assets/icon_mail.png
  15. Landing Page Car Rent/assets/icon_price.png
  15. Landing Page Car Rent/assets/icon_professional.png
  15. Landing Page Car Rent/assets/icon_twitch.png
  15. Landing Page Car Rent/assets/icon_twitter.png
  15. Landing Page Car Rent/assets/img_car.png
  15. Landing Page Car Rent/assets/img_photo-1.png
  15. Landing Page Car Rent/assets/img_photo-2.png
  15. Landing Page Car Rent/assets/img_photo.png
  15. Landing Page Car Rent/assets/img_service.png
  15. Landing Page Car Rent/assets/left-button.svg
  15. Landing Page Car Rent/assets/right-button.svg
  15. Landing Page Car Rent/assets/testi.png
  15. Landing Page Car Rent/assets/testi2.png
  15. Landing Page Car Rent/index.html
  15. Landing Page Car Rent/style/responsive.css
  15. Landing Page Car Rent/style/style.css
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#61 Text Modifier
  25.Text Modifier/.npmignore
  25.Text Modifier/package-lock.json
  25.Text Modifier/text/.gitignore
  25.Text Modifier/text/README.md
  25.Text Modifier/text/package-lock.json
  25.Text Modifier/text/package.json
  25.Text Modifier/text/public/favicon.ico
  25.Text Modifier/text/public/index.html
  25.Text Modifier/text/public/logo192.png
  25.Text Modifier/text/public/logo512.png
  25.Text Modifier/text/public/manifest.json
  25.Text Modifier/text/public/robots.txt
  25.Text Modifier/text/src/App.css
  25.Text Modifier/text/src/App.js
  25.Text Modifier/text/src/App.test.js
  25.Text Modifier/text/src/components/Navbar.js
  25.Text Modifier/text/src/components/TextForm.js
  25.Text Modifier/text/src/index.css
  25.Text Modifier/text/src/index.js
  25.Text Modifier/text/src/logo.svg
  25.Text Modifier/text/src/reportWebVitals.js
  25.Text Modifier/text/src/setupTests.js
Labels: enhancement, hacktoberfest-accepted, Ready to Merge

#64 Adding HTML static webpage ( Steve Jobs Timeline Webpage )
  Steve-Jobs-Timeline-webpage/image.jpg
  Steve-Jobs-Timeline-webpage/index.html
  Steve-Jobs-Timeline-webpage/sign.png
Labels: good first issue, hacktoberfest-accepted, Ready to Merge

#67 Facebook Clone using React Js
  Facebook_clone_ReactJs/src/App.css
  Facebook_clone_ReactJs/src/App.jsx
  Facebook_clone_ReactJs/src/Feed.jsx
  Facebook_clone_ReactJs/src/Header.jsx
  Facebook_clone_ReactJs/src/Login.jsx
  Facebook_clone_ReactJs/src/MessageSender.jsx
  Facebook_clone_ReactJs/src/Post.jsx
  Facebook_clone_ReactJs/src/Sidebar.jsx
  Facebook_clone_ReactJs/src/SidebarRow.css
  Facebook_clone_ReactJs/src/SidebarRow.jsx
  Facebook_clone_ReactJs/src/Story.css
  Facebook_clone_ReactJs/src/Story.jsx
  Facebook_clone_ReactJs/src/StoryReel.jsx
  Facebook_clone_ReactJs/src/Widgets.jsx
  Facebook_clone_ReactJs/src/assets/react.svg
  Facebook_clone_ReactJs/src/feed.css
  Facebook_clone_ReactJs/src/header.css
  Facebook_clone_ReactJs/src/index.css
  Facebook_clone_ReactJs/src/login.css
  Facebook_clone_ReactJs/src/main.jsx
  Facebook_clone_ReactJs/src/messagesender.css
  Facebook_clone_ReactJs/src/post.css
  Facebook_clone_ReactJs/src/sidebar.css
  Facebook_clone_ReactJs/src/storyreel.css
  Facebook_clone_ReactJs/src/widgets.css
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#74 Added Analog Clock Project and Updated the table of contents
  26. Analog Clock/index.html
  26. Analog Clock/script.js
  26. Analog Clock/style.css
  README.md
Labels: enhancement, hacktoberfest-accepted, Ready to Merge

#79 new web dev project added
  26. Responsive omnifood project/content.md
  26. Responsive omnifood project/css/general.css
  26. Responsive omnifood project/css/queries.css
  26. Responsive omnifood project/css/style.css
  26. Responsive omnifood project/img/app/app-screen-1.png
  26. Responsive omnifood project/img/app/app-screen-2.png
  26. Responsive omnifood project/img/app/app-screen-3.png
  26. Responsive omnifood project/img/customers/ben.jpg
  26. Responsive omnifood project/img/customers/customer-1.jpg
  26. Responsive omnifood project/img/customers/customer-2.jpg
  26. Responsive omnifood project/img/customers/customer-3.jpg
  26. Responsive omnifood project/img/customers/customer-4.jpg
  26. Responsive omnifood project/img/customers/customer-5.jpg
  26. Responsive omnifood project/img/customers/customer-6.jpg
  26. Responsive omnifood project/img/customers/dave.jpg
  26. Responsive omnifood project/img/customers/hannah.jpg
  26. Responsive omnifood project/img/customers/steve.jpg
  26. Responsive omnifood project/img/eating.jpg
  26. Responsive omnifood project/img/favicon.png
  26. Responsive omnifood project/img/gallery/gallery-1.jpg
  26. Responsive omnifood project/img/gallery/gallery-10.jpg
  26. Responsive omnifood project/img/gallery/gallery-11.jpg
  26. Responsive omnifood project/img/gallery/gallery-12.jpg
  26. Responsive omnifood project/img/gallery/gallery-2.jpg
  26. Responsive omnifood project/img/gallery/gallery-3.jpg
  26. Responsive omnifood project/img/gallery/gallery-4.jpg
  26. Responsive omnifood project/img/gallery/gallery-5.jpg
  26. Responsive omnifood project/img/gallery/gallery-6.jpg
  26. Responsive omnifood project/img/gallery/gallery-7.jpg
  26. Responsive omnifood project/img/gallery/gallery-8.jpg
  26. Responsive omnifood project/img/gallery/gallery-9.jpg
  26. Responsive omnifood project/img/hero.png
  26. Responsive omnifood project/img/logos/business-insider.png
  26. Responsive omnifood project/img/logos/forbes.png
  26. Responsive omnifood project/img/logos/techcrunch.png
  26. Responsive omnifood project/img/logos/the-new-york-times.png
  26. Responsive omnifood project/img/logos/usa-today.png
  26. Responsive omnifood project/img/meals/meal-1.jpg
  26. Responsive omnifood project/img/meals/meal-2.jpg
  26. Responsive omnifood project/img/omnifood-logo.png
  26. Responsive omnifood project/index.html
Labels: hacktoberfest-accepted, kick-starter, Ready to Merge

#94 updated README.md table content till number 35
  README.md
Labels: documentation, hacktoberfest-accepted

#77 Added official CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest-accepted, Ready to Merge

#93 Created Food delivery website design
  39. Food delivery website design/Readme.md
  39. Food delivery website design/fooditem.js
  39. Food delivery website design/images/biryani/Ambur-Chicken-Biryani.jpg
  39. Food delivery website design/images/biryani/Chicken-Biryani-hyd.jpg
  39. Food delivery website design/images/biryani/egg-biryani.jpg
  39. Food delivery website design/images/biryani/goan-fish-biryani.jpg
  39. Food delivery website design/images/biryani/hyd-Mutton-Biryani.jpg
  39. Food delivery website design/images/biryani/kamrupi-biryani.jpg
  39. Food delivery website design/images/biryani/kashmiri.pulao.jpg
  39. Food delivery website design/images/biryani/memonibiryani.png
  39. Food delivery website design/images/biryani/mughlai-biryani.jpg
  39. Food delivery website design/images/chicken/Chicken-Curry.jpg
  39. Food delivery website design/images/chicken/Chicken-Masala.jpg
  39. Food delivery website design/images/chicken/Chicken-do-Pyaza.jpg
  39. Food delivery website design/images/chicken/Chicken_roast.jpg
  39. Food delivery website design/images/chicken/Handi-chicken.jpg
  39. Food delivery website design/images/chicken/Murgh-Musallam.jpg
  39. Food delivery website design/images/chicken/Paneer-Butter-Masala.jpg
  39. Food delivery website design/images/chinese/ChickenManchurian.jpg
  39. Food delivery website design/images/chinese/Chili-Chicken.jpg
  39. Food delivery website design/images/chinese/cabbage-momos-.jpg
  39. Food delivery website design/images/chinese/chowmin.jpg
  39. Food delivery website design/images/chinese/mmos.jpg
  39. Food delivery website design/images/chinese/spring-rolls.jpg
  39. Food delivery website design/images/chinese/szechuan-chicken.jpg
  39. Food delivery website design/images/chinese/veg-fried-rice.jpg
  39. Food delivery website design/images/foodie hunter.png
  39. Food delivery website design/images/foodielogo.png
  39. Food delivery website design/images/paneer/Matar-Paneer.jpg
  39. Food delivery website design/images/paneer/Paneer-Do-Pyaza.jpg
  39. Food delivery website design/images/paneer/Paneer-Hyderabadi.jpg
  39. Food delivery website design/images/paneer/palak-paneer.jpg
  39. Food delivery website design/images/paneer/paneer-butter-masala.jpg
  39. Food delivery website design/images/paneer/paneer-lababdar.jpg
  39. Food delivery website design/images/paneer/shahi-paneer.jpg
  39. Food delivery website design/images/paneer/vegetable-curry.jpg
  39. Food delivery website design/images/south indian/Butter-Masala-Dosa.png
  39. Food delivery website design/images/south indian/Rava-Uttapam.jpg
  39. Food delivery website design/images/south indian/idli-with-rice-flour.jpg
  39. Food delivery website design/images/south indian/masala-dosa.jpg
  39. Food delivery website design/images/south indian/mysore-bonda.jpg
  39. Food delivery website design/images/south indian/onion-uttapam.jpg
  39. Food delivery website design/images/south indian/plain-dosa.jpg
  39. Food delivery website design/images/south indian/sambhar-vada.jpg
  39. Food delivery website design/images/vegetable/VEG-JALFREZI.jpg
  39. Food delivery website design/images/vegetable/navratan-korma_-vegetable.png
  39. Food delivery website design/images/vegetable/vegetable-biryani.jpg
  39. Food delivery website design/images/vegetable/vegetable-curry.jpg
  39. Food delivery website design/images/vegetable/vegetable-kolhapuri.jpg
  39. Food delivery website design/images/vegetable/vegetable-masala.jpg
  39. Food delivery website design/images/vegetable/vegetable-pakora.jpg
  39. Food delivery website design/index.css
  39. Food delivery website design/index.html
  39. Food delivery website design/index.js
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#98 Added a random Password generator web app
  40. Javascript Password generator/Readme.md
  40. Javascript Password generator/index.html
  40. Javascript Password generator/mega.js
  40. Javascript Password generator/style.css
Labels: good first issue, hacktoberfest-accepted

#105 Movie app
  41. Movie API List/112815904-no-image-available-icon-flat-vector-illustration.webp
  41. Movie API List/README.md
  41. Movie API List/TV/TV.html
  41. Movie API List/TV/app.js
  41. Movie API List/TV/style.css
  41. Movie API List/app.js
  41. Movie API List/index.html
  41. Movie API List/style.css
Labels: enhancement, hacktoberfest-accepted, Awesome

#97 A quiz app made with pure js
  26. Harry Potter CLI Quiz App with Javascript/README.md
  26. Harry Potter CLI Quiz App with Javascript/index.js
Labels: enhancement, hacktoberfest-accepted, Ready to Merge

#99 ADD: added webdev project
  39. Instagram_login_signup_page clone/appstore.png
  39. Instagram_login_signup_page clone/fb.jpg
  39. Instagram_login_signup_page clone/img.png
  39. Instagram_login_signup_page clone/img2].png
  39. Instagram_login_signup_page clone/img3.png
  39. Instagram_login_signup_page clone/img4.png
  39. Instagram_login_signup_page clone/img5.png
  39. Instagram_login_signup_page clone/index.html
  39. Instagram_login_signup_page clone/logo.jpg
  39. Instagram_login_signup_page clone/logo.png
  39. Instagram_login_signup_page clone/phone.png
  39. Instagram_login_signup_page clone/playstore.png
  39. Instagram_login_signup_page clone/style.css
Labels: enhancement, hacktoberfest-accepted, Ready to Merge

#110 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#117 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, Ready to Merge

#115 Spy Number Checker
  47. Spy number/index.html
  47. Spy number/script.js
  47. Spy number/style.css
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#119 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#121 Added files for Simon game Closes #116
  48. Simon game/blue.mp3
  48. Simon game/green.mp3
  48. Simon game/index.html
  48. Simon game/index.js
  48. Simon game/indexWorking.js
  48. Simon game/logo.jpg
  48. Simon game/red.mp3
  48. Simon game/styles.css
  48. Simon game/wrong.mp3
  48. Simon game/yellow.mp3
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#126 Abhi's JS Calender
  49. Javascript Calender/app.css
  49. Javascript Calender/app.js
  49. Javascript Calender/index.html
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#128 abhi's SignUp SignIn form
  50. Sliding SignUp-SignIn Form/app.js
  50. Sliding SignUp-SignIn Form/index.html
  50. Sliding SignUp-SignIn Form/log.svg
  50. Sliding SignUp-SignIn Form/register.svg
  50. Sliding SignUp-SignIn Form/style.css
Labels: enhancement, hacktoberfest-accepted, Awesome, Ready to Merge

#109 Scientific calculator added
  FLIPKART CLONE/css/responsive.css
  FLIPKART CLONE/css/style.css
  FLIPKART CLONE/css/utils.css
  FLIPKART CLONE/index.html
  FLIPKART CLONE/logo.png
  Scientific_calculator/index.html
  Scientific_calculator/script.js
  Scientific_calculator/style.css
Labels: hacktoberfest-accepted, Ready to Merge

#111 Simple ToDo List App
  Simple To Do List App/index.html
  Simple To Do List App/script.js
  Simple To Do List App/small.css
  Simple To Do List App/style.css
Labels: good first issue, hacktoberfest-accepted

#89 Added an App that converts normal sentences to yoda sentences
  26. Yoda Translator App/README.md
  26. Yoda Translator App/app.js
  26. Yoda Translator App/images/github-icon-1.svg
  26. Yoda Translator App/images/github.png
  26. Yoda Translator App/images/linkedin-icon.svg
  26. Yoda Translator App/images/twitter-6.svg
  26. Yoda Translator App/images/twitter.png
  26. Yoda Translator App/images/yoda-icon-18.ico
  26. Yoda Translator App/index.html
  26. Yoda Translator App/styles.css
Labels: enhancement, hacktoberfest-accepted

#90 A weather forecasting web app
  Stadium landing page/js/index.js
  Stadium landing page/media/Screenshot from 2022-01-10 22-44-45.png
  Stadium landing page/media/close_icon.svg
  Stadium landing page/media/gXUClIR.gif
  Weather/Background.jpg
  Weather/app.js
  Weather/index.html
  Weather/style.css
  Weather/unknown.png
Labels: hacktoberfest-accepted, Ready to Merge

#127 Book Finder Project Added
  .vscode/settings.json
  Book Finder/index.html
  Book Finder/main.js
  Book Finder/style.css
Labels: hacktoberfest-accepted, Awesome, Need Configuration

#131 added 57.Color Game
  57. Color Game/index.html
  57. Color Game/indexhard.html
  57. Color Game/scripteasy.js
  57. Color Game/scripthard.js
  57. Color Game/styleeasy.css
  57. Color Game/stylehard.css
Labels: good first issue, hacktoberfest-accepted, Ready to Merge

#69 Random Meme Generator
  Random Meme Generator/index.html
  Random Meme Generator/loading.gif
  Random Meme Generator/main.js
  Random Meme Generator/style.css
Labels: enhancement, hacktoberfest-accepted

#136 A responsive Starbucks Clone.
  62.Starbucks Clone/137-79281.jpg
  62.Starbucks Clone/Back-2-School.jpg
  62.Starbucks Clone/Summers.jpg
  62.Starbucks Clone/casicielo.jpg
  62.Starbucks Clone/index.html
  62.Starbucks Clone/logo.png
  62.Starbucks Clone/resp.css
  62.Starbucks Clone/rewards.jpg
  62.Starbucks Clone/style.css
Labels: enhancement, hacktoberfest-accepted, Ready to Merge

#138 Hangman Game
  63. Hangman Game/indexhangman.html
  63. Hangman Game/script.js
  63. Hangman Game/style.css
Labels: hacktoberfest-accepted, kick-starter, Ready to Merge

#149 Adding Rock Paper Scissors Game
  Rock-Paper-Scissors-Game/Readme.md.txt
  Rock-Paper-Scissors-Game/index.html
  Rock-Paper-Scissors-Game/script.js
  Rock-Paper-Scissors-Game/style.css
Labels: enhancement, hacktoberfest-accepted, kick-starter

#155 Go URL Shortener
  64. Go URL Shortener/api/.env
  64. Go URL Shortener/api/Dockerfile
  64. Go URL Shortener/api/database/database.go
  64. Go URL Shortener/api/go.mod
  64. Go URL Shortener/api/go.sum
  64. Go URL Shortener/api/helpers/helpers.go
  64. Go URL Shortener/api/main.go
  64. Go URL Shortener/api/routes/resolve.go
  64. Go URL Shortener/api/routes/shorten.go
  64. Go URL Shortener/db/Dockerfile
  64. Go URL Shortener/docker-compose.yml
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#161 Added Currency Exchange Rate Calculator
  64. Currency Exchange Rate Calculator/README.md
  64. Currency Exchange Rate Calculator/assets/image/money.png
  64. Currency Exchange Rate Calculator/index.html
  64. Currency Exchange Rate Calculator/script.js
  64. Currency Exchange Rate Calculator/style.css
Labels: enhancement, hacktoberfest-accepted, Ready to Merge

#162 Schedule Your Days
  64. Schedule Your Day/build/asset-manifest.json
  64. Schedule Your Day/build/favicon.ico
  64. Schedule Your Day/build/index.html
  64. Schedule Your Day/build/logo192.png
  64. Schedule Your Day/build/logo512.png
  64. Schedule Your Day/build/manifest.json
  64. Schedule Your Day/build/robots.txt
  64. Schedule Your Day/build/static/css/main.137d19ec.css
  64. Schedule Your Day/build/static/css/main.137d19ec.css.map
  64. Schedule Your Day/build/static/js/787.55e404cb.chunk.js
  64. Schedule Your Day/build/static/js/787.55e404cb.chunk.js.map
  64. Schedule Your Day/build/static/js/main.b030abfe.js
  64. Schedule Your Day/build/static/js/main.b030abfe.js.LICENSE.txt
  64. Schedule Your Day/build/static/js/main.b030abfe.js.map
  64. Schedule Your Day/build/static/media/trash.c4e35861d2606e76ed78.png
Labels: hacktoberfest-accepted, kick-starter, Ready to Merge

#163 Swiggy Clone
  64. Swiggy Clone/index.html
  64. Swiggy Clone/static/css/style.css
  64. Swiggy Clone/static/icon/favicon.ico
  64. Swiggy Clone/static/images/astore.png
  64. Swiggy Clone/static/images/dinner.jfif
  64. Swiggy Clone/static/images/feature1.png
  64. Swiggy Clone/static/images/feature2.png
  64. Swiggy Clone/static/images/feature3.png
  64. Swiggy Clone/static/images/gplay.png
  64. Swiggy Clone/static/images/logo.png
  64. Swiggy Clone/static/images/logo1.png
  64. Swiggy Clone/static/images/mobile1.png
  64. Swiggy Clone/static/images/mobile2.png
  64. Swiggy Clone/static/images/social1.png
  64. Swiggy Clone/static/images/social2.png
  64. Swiggy Clone/static/images/social3.png
  64. Swiggy Clone/static/images/social4.png
Labels: hacktoberfest-accepted, Ready to Merge

#165 SpaceX Clone Using ReactJs
  SpaceX-Clone/.gitignore
  SpaceX-Clone/index.html
  SpaceX-Clone/package-lock.json
  SpaceX-Clone/package.json
  SpaceX-Clone/src/App.jsx
  SpaceX-Clone/src/Components/Banner.jsx
  SpaceX-Clone/src/Components/BannerItem.jsx
  SpaceX-Clone/src/Components/Footer.jsx
  SpaceX-Clone/src/Components/Header.jsx
  SpaceX-Clone/src/index.css
  SpaceX-Clone/src/main.jsx
  SpaceX-Clone/vite.config.js
Labels: hacktoberfest-accepted, Awesome, Ready to Merge

#169 made a BMI Calculator
  .vscode/settings.json
  65. BMI Calculator/Index.html
  65. BMI Calculator/background.png
  65. BMI Calculator/script.js
  65. BMI Calculator/style.css
Labels: good first issue, hacktoberfest-accepted, Ready to Merge

#170 Apple Landing Page.
  65.Apple/img/apple-logo.png
  65.Apple/img/magnifier.png
  65.Apple/img/shopping-bag.png
  65.Apple/img/store-chat-specialist-icon-202208.jpeg
  65.Apple/main/index.html
  65.Apple/main/style.css
  65.Apple/prodcuts/store-card-13-accessories-nav-202203.png
  65.Apple/prodcuts/store-card-13-airpods-nav-202110.png
  65.Apple/prodcuts/store-card-13-airtags-nav-202108.png
  65.Apple/prodcuts/store-card-13-appletv-nav-202108.png
  65.Apple/prodcuts/store-card-13-homepod-nav-202110.png
  65.Apple/prodcuts/store-card-13-ipad-nav-202108.png
  65.Apple/prodcuts/store-card-13-iphone-nav-202109_GEO_EMEA.png
  65.Apple/prodcuts/store-card-13-mac-nav-202203.png
  65.Apple/prodcuts/store-card-13-watch-nav-202203.png
Labels: enhancement, hacktoberfest-accepted, Ready to Merge

#173 Added a react based breakingBadTrivia application
  Breaking Bad Trivia/.gitignore
  Breaking Bad Trivia/README.md
  Breaking Bad Trivia/package-lock.json
  Breaking Bad Trivia/package.json
  Breaking Bad Trivia/public/favicon.ico
  Breaking Bad Trivia/public/index.html
  Breaking Bad Trivia/public/logo192.png
  Breaking Bad Trivia/public/logo512.png
  Breaking Bad Trivia/public/manifest.json
  Breaking Bad Trivia/public/robots.txt
  Breaking Bad Trivia/src/App.css
  Breaking Bad Trivia/src/App.js
  Breaking Bad Trivia/src/components/CharacterCard.js
  Breaking Bad Trivia/src/components/CharacterGrid.js
  Breaking Bad Trivia/src/components/Footer.js
  Breaking Bad Trivia/src/components/Header.js
  Breaking Bad Trivia/src/components/SearchBar.js
  Breaking Bad Trivia/src/components/Spinner.js
  Breaking Bad Trivia/src/img/bg.jpg
  Breaking Bad Trivia/src/img/logo.png
  Breaking Bad Trivia/src/img/spinner.gif
  Breaking Bad Trivia/src/index.js
Labels: enhancement, hacktoberfest-accepted, kick-starter, Ready to Merge
